<style>
	code{ font-family:'Courier New',Courier, serif;}
	</style>
<div class="bg-white px-6 py-32 lg:px-8">
  <div class="mx-auto max-w-3xl text-base leading-7 text-gray-700">
    <p class="text-base font-semibold leading-7 text-indigo-600">Documentation</p>
    <h1 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Using the counters</h1>
    
    <p>How to use Counterify API</p>
	    
	    
    <p class="mt-6 text-xl leading-8">
	     In the context of counters, integrations allow data to be automatically pushed from external sources into a counter, without the need for manual data entry. 
	    
    </p>
    
    <code class="bg-gray-50 border-gray-200 border px-3 py-3 block text-sm rounded-md">
    
    <strong>API Main Endpoint:</strong><br>
     https://api.counterify.com<br><br>
     <strong>Token Bearer</strong><br>
     <?= $_SESSION['user']['bearer']; ?>
    
    </code>
	
	
    <div class="mt-10 max-w-2xl">
      <p>To push data to counters via API, businesses can use any programming language that supports HTTP requests, such as PHP or JavaScript. For example, a PHP script could be used to send data from a form on a website directly to a counter via an API call. Similarly, a JavaScript function could be used to send data from a web application to a counter, allowing real-time tracking of user behavior.
<br><br>
   <ul role="list" class="mt-8 max-w-xl space-y-8 text-gray-600">
        <li class="flex gap-x-3">
          <svg class="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
          </svg>
          <span><strong class="font-semibold text-gray-900">Directly from the browser</strong> Ping attribute, ping="https://app.counterify.com/ ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.</span>
        </li>
        <li class="flex gap-x-3">
          <svg class="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
          </svg>
          <span><strong class="font-semibold text-gray-900">Loops.</strong> Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo.</span>
        </li>
        <li class="flex gap-x-3">
          <svg class="mt-1 h-5 w-5 flex-none text-indigo-600" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
          </svg>
          <span><strong class="font-semibold text-gray-900">Events.</strong> Ac tincidunt sapien vehicula erat auctor pellentesque rhoncus. Et magna sit morbi lobortis.</span>
        </li>
      </ul>
      
In addition to API integrations, counters can also be updated manually via the dashboard. This is useful for businesses that want to track data that is not generated by an external system, such as data from offline sources or from manual data entry. By manually updating counters, businesses can still benefit from the powerful tracking and analysis tools provided by counters, without needing to rely on automated data sources.
<br><br>
Overall, integrations provide a flexible and powerful way to track and analyze data, whether it is generated automatically by software systems or manually entered by users. By using integrations to feed data into counters, businesses can gain valuable insights into their operations and make data-driven decisions to drive success.</p>


<h2 class="mt-16 text-2xl font-bold tracking-tight text-gray-900">Examples in different languages</h2>
<p>Examples in different languages of a POST request to send +1 (or + any value) to any counter. If the counter doesn't exist it will be created</p>
	
	


<h3 class="mt-10 text-lg font-bold tracking-tight text-gray-900">cURL example</h3>
	<code class="bg-gray-50 border-gray-200 border px-3 py-3 block text-sm rounded-md"><pre>curl -X POST 
  -H "Authorization: Bearer <?= $_SESSION['user']['bearer']; ?>" 
  -H "Content-Type: application/json" 
  -d '{"kpi": "Counter label or name", "value": "1"}' 
  https://api.counterify.com
	</pre></code>

<h3 class="mt-10 text-lg font-bold tracking-tight text-gray-900">PHP example</h3>

<code class="bg-gray-50 border-gray-200 border px-3 py-3 block text-sm rounded-md"><pre>$token = '<?= $_SESSION['user']['bearer']; ?>';

		$url = 'https://api.counterify.com';

		$params = array(
		  'kpi' => $key, // string
		  'value' => $value // integer
		);

		$headers = array(
		  'Authorization: Bearer ' . $token,
		  'Content-Type: application/json'
		);

		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_POST, true);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($params));
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		$response = curl_exec($ch);
		curl_close($ch);
</pre></code>


   
      <p class="mt-8">Et vitae blandit facilisi magna lacus commodo. Vitae sapien duis odio id et. Id blandit molestie auctor fermentum dignissim. Lacus diam tincidunt ac cursus in vel. Mauris varius vulputate et ultrices hac adipiscing egestas. Iaculis convallis ac tempor et ut. Ac lorem vel integer orci.</p>
       </div>
</div>
