
<div class=" px-6 py-16 pb-8 sm:pt-32 sm:pb-16 lg:px-8 border-gray-800 border-b">
  <div class="mx-auto max-w-2xl text-center">
    <h1 class="text-4xl font-bold tracking-tight text-white sm:text-6xl nunito">{Country}</h1>
    <p class="mt-4 text-sm leading-8 text-gray-500">List of domains by country, country is determined from the IP</p>
  </div>
</div>




<section class="text-gray-100 my-2 w-full px-4 overflow-hidden">
    <ul class="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6">
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/"></a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/"></a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AD">AD</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AE">AE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AF">AF</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AG">AG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AL">AL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AM">AM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AO">AO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AR">AR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AT">AT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AU">AU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AW">AW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AX">AX</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/AZ">AZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BA">BA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BB">BB</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BD">BD</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BE">BE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BF">BF</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BG">BG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BH">BH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BI">BI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BL">BL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BM">BM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BN">BN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BO">BO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BR">BR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BS">BS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BT">BT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BW">BW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BY">BY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/BZ">BZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CA">CA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CD">CD</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CH">CH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CI">CI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CL">CL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CM">CM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CN">CN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CO">CO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CR">CR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CU">CU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CV">CV</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CW">CW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CY">CY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/CZ">CZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/DE">DE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/DJ">DJ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/DK">DK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/DN">DN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/DO">DO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/DZ">DZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/EC">EC</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/EE">EE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/EG">EG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/ES">ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/ET">ET</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/EU">EU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/FI">FI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/FJ">FJ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/FO">FO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/FR">FR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GA">GA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GB">GB</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GE">GE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GG">GG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GH">GH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GI">GI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GL">GL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GR">GR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GT">GT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/GU">GU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/HK">HK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/HM">HM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/HN">HN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/HR">HR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/HU">HU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/ID">ID</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/IE">IE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/IL">IL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/IM">IM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/IN">IN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/IQ">IQ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/IR">IR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/IS">IS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/IT">IT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/JE">JE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/JM">JM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/JO">JO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/JP">JP</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KE">KE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KG">KG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KH">KH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KM">KM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KN">KN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KP">KP</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KR">KR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KW">KW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KY">KY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/KZ">KZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LA">LA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LB">LB</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LI">LI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LK">LK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LS">LS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LT">LT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LU">LU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LV">LV</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/LY">LY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MA">MA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MC">MC</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MD">MD</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/ME">ME</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MF">MF</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MG">MG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MK">MK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/ML">ML</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MM">MM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MN">MN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MO">MO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MP">MP</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MQ">MQ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MT">MT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MU">MU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MV">MV</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MW">MW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MX">MX</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MY">MY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/MZ">MZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NA">NA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NC">NC</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NE">NE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NG">NG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NI">NI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NL">NL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NO">NO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NP">NP</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NR">NR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/NZ">NZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/OM">OM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PA">PA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PE">PE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PF">PF</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PG">PG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PH">PH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PK">PK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PL">PL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PM">PM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PO">PO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PR">PR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PS">PS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PT">PT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PW">PW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/PY">PY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/QA">QA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/RE">RE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/RO">RO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/RS">RS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/RU">RU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/RW">RW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SA">SA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SB">SB</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SC">SC</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SE">SE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SG">SG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SI">SI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SK">SK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SL">SL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SM">SM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SO">SO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SR">SR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/ST">ST</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SV">SV</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SW">SW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SY">SY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/SZ">SZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TG">TG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TH">TH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TJ">TJ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TL">TL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TM">TM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TN">TN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TO">TO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TR">TR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TT">TT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TU">TU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TW">TW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/TZ">TZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/UA">UA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/UG">UG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/US">US</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/UY">UY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/UZ">UZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/VA">VA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/VC">VC</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/VE">VE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/VG">VG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/VN">VN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/VU">VU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/WF">WF</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/WS">WS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/YE">YE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/ZA">ZA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/country/ZW">ZW</a></li>
        </ul>
</section>
