
<div class=" px-6 py-24 pb-8 sm:pt-32 sm:pb-16 lg:px-8 border-gray-800 border-b">
  <div class="mx-auto max-w-2xl text-center">
    <h1 class="text-4xl font-bold tracking-tight text-white sm:text-6xl nunito">Domains by Language</h1>
    <p class="mt-4 text-sm leading-8 text-gray-500">List of languages found inwebsites</p>
  </div>
</div>
<section class="text-gray-100 my-2 w-full px-4 overflow-hidden">
    <ul class="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6">
       
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/af">af</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/af-ZA">af-ZA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/al">al</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/am">am</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar">ar</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar_DZ">ar_DZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar_SA">ar_SA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-00">ar-00</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-aa">ar-aa</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-AE">ar-AE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-AR">ar-AR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-dz">ar-dz</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-EG">ar-EG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-IQ">ar-IQ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-JO">ar-JO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-KW">ar-KW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-MA">ar-MA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-SA">ar-SA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-SY">ar-SY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ar-TN">ar-TN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/ar">ar</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/arg">arg</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ary">ary</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/at">at</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/at-AT">at-AT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/auto">auto</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/az">az</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/az-AZ">az-AZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/az-La">az-La</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ba">ba</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/be">be</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/be-nl">be-nl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bg">bg</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bg-BG">bg-BG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bm">bm</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bn">bn</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bn_BD">bn_BD</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bn-BD">bn-BD</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/br">br</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/br-pt">br-pt</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bs">bs</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bs-BA">bs-BA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/bu">bu</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ca">ca</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ca_ES">ca_ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ca-CA">ca-CA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ca-ct">ca-ct</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ca-ES">ca-ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/caste">caste</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cat">cat</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cat-E">cat-E</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cc-ar">cc-ar</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ceb">ceb</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ch">ch</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ch-cn">ch-cn</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/chi">chi</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/chine">chine</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ckb-i">ckb-i</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cmn-H">cmn-H</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cn">cn</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/code">code</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/croat">croat</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cs">cs</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cs_CZ">cs_CZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cs-CS">cs-CS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cs-CZ">cs-CZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ct">ct</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cv">cv</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cz">cz</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/cz-CS">cz-CS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/da">da</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/da-DK">da-DK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/de">de</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/de_AT">de_AT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/de_CH">de_CH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/de_DE">de_DE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/de-at">de-at</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/de-CH">de-CH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/de-DE">de-DE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/defau">defau</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/dir=">dir=</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/dk">dk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/dr">dr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/dv">dv</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/dz">dz</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/eb">eb</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ee">ee</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/el">el</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/el-gr">el-gr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en      ">en        </a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en">en</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en us">en us</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_AU">en_AU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_CA">en_CA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_EN">en_EN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_GB">en_GB</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_HK">en_HK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_IE">en_IE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_IN">en_IN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_UK">en_UK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en_us">en_us</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-00">en-00</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ae">en-ae</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-AU">en-AU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-AZ">en-AZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-be">en-be</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ca">en-ca</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ce">en-ce</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-CN">en-CN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-CZ">en-CZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-DE">en-DE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ed">en-ed</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-EN">en-EN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ES">en-ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-eu">en-eu</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-GB">en-GB</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-HK">en-HK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ID">en-ID</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-IE">en-IE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-in">en-in</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-IT">en-IT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ke">en-ke</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-KH">en-KH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-LK">en-LK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-MY">en-MY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-NG">en-NG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-nl">en-nl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-NZ">en-NZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-PH">en-PH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-PK">en-PK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-PT">en-PT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-SA">en-SA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-SG">en-SG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-TR">en-TR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-TW">en-TW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-UK">en-UK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-US">en-US</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-vi">en-vi</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-wr">en-wr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ZA">en-ZA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-zh">en-zh</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en-ZZ">en-ZZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en, e">en, e</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en,en">en,en</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/en2">en2</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/eng">eng</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/Engli">Engli</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ENH">ENH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es  p">es   p</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es">es</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es  p">es  p</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es e.">es e.</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es pr">es pr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es_41">es_41</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es_AR">es_AR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es_CO">es_CO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es_ES">es_ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es_MX">es_MX</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es_US">es_US</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-41">es-41</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-AD">es-AD</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-AR">es-AR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-BO">es-BO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-CA">es-CA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-cl">es-cl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-CO">es-CO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-CR">es-CR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-CU">es-CU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-DO">es-DO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-EC">es-EC</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-ES">es-ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-GL">es-GL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-GT">es-GT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-HN">es-HN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-LA">es-LA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-MX">es-MX</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-NI">es-NI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-ol">es-ol</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-PA">es-PA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-PE">es-PE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-PR">es-PR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-PY">es-PY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-SV">es-SV</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-US">es-US</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-UY">es-UY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-VE">es-VE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es-wp">es-wp</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es,">es,</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es, e">es, e</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es, f">es, f</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/es,pt">es,pt</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/esMX">esMX</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/esp">esp</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/EspaÃ">EspaÃ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/et">et</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/et-EE">et-EE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/eu">eu</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/eu-ES">eu-ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/EUR-E">EUR-E</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ew">ew</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ez">ez</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fa">fa</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fa_IR">fa_IR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fa-IR">fa-IR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fi">fi</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fi_FI">fi_FI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fi-FI">fi-FI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fo">fo</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fo-FO">fo-FO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr">fr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr_BE">fr_BE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr_CA">fr_CA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr_CH">fr_CH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr_FR">fr_FR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr-be">fr-be</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr-CA">fr-CA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr-CH">fr-CH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr-FR">fr-FR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr-LU">fr-LU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr-MA">fr-MA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/fr-TN">fr-TN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ga">ga</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/gal">gal</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/gb">gb</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/gb231">gb231</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ge">ge</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ge-GE">ge-GE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/gl">gl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/gl-ES">gl-ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/gr">gr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hb">hb</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/he">he</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/he-HE">he-HE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/he-IL">he-IL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hi">hi</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hi-IN">hi-IN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hr">hr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hr-hr">hr-hr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hu">hu</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hu-HU">hu-HU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hy">hy</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/hy-AM">hy-AM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/id">id</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/id_ID">id_ID</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/id-ID">id-ID</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/id, i">id, i</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/il">il</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/in">in</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/in-en">in-en</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ir_fa">ir_fa</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ir-fa">ir-fa</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/is">is</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/it">it</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/it_IT">it_IT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/it-IT">it-IT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ita">ita</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/iv">iv</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/iw">iw</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ja">ja</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ja_JP">ja_JP</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ja-JA">ja-JA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ja-JP">ja-JP</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ja,zh">ja,zh</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/jn">jn</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/jp">jp</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ka">ka</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ka-GE">ka-GE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/kk">kk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/km">km</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/km-KH">km-KH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ko">ko</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ko_KR">ko_KR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ko-KO">ko-KO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ko-KR">ko-KR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/kr">kr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ku">ku</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/kz-kz">kz-kz</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/la">la</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/lang=">lang=</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/lk">lk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/lo">lo</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/lt">lt</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/lt_LT">lt_LT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/lt-LT">lt-LT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/lv">lv</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/lv-LV">lv-LV</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ma">ma</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mk">mk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mk-MK">mk-MK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ml">ml</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ml-IN">ml-IN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mm-mm">mm-mm</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mn">mn</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mr">mr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mr-IN">mr-IN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ms">ms</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ms-MY">ms-MY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mt">mt</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mul">mul</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/mx">mx</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/my">my</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/my-MM">my-MM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nb">nb</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nb_NO">nb_NO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nb-NO">nb-NO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ne">ne</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ne-NP">ne-NP</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nep">nep</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nl">nl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nl_be">nl_be</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nl_NL">nl_NL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nl-BE">nl-BE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nl-ES">nl-ES</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nl-NL">nl-NL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nn">nn</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/nn-NO">nn-NO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/no">no</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/no-NO">no-NO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/None">None</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/np">np</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/oc">oc</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/og:">og:</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/or">or</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/persi">persi</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ph">ph</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pk">pk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pl">pl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pl_PL">pl_PL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pl-PL">pl-PL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pr">pr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ps">ps</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pt">pt</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pt_br">pt_br</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pt_PT">pt_PT</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pt-AO">pt-AO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pt-BR">pt-BR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pt-pr">pt-pr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/pt-pt">pt-pt</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ro">ro</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ro_RO">ro_RO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ro-RO">ro-RO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/rs">rs</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ru      ">ru        </a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ru">ru</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ru_RU">ru_RU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ru-KZ">ru-KZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ru-RU">ru-RU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ru-TM">ru-TM</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ru-ua">ru-ua</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ru-UK">ru-UK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/rua-R">rua-R</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/s1">s1</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/SA">SA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/scott">scott</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/SE">SE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sh">sh</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ShopL">ShopL</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/si">si</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/si-LK">si-LK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/si-SI">si-SI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sk">sk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sk_SK">sk_SK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sk-SK">sk-SK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sl">sl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sl-SI">sl-SI</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/slo">slo</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/so">so</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sp">sp</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/spa">spa</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/Spani">Spani</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sq">sq</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sq,en">sq,en</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sr">sr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sr-Cy">sr-Cy</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sr-La">sr-La</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sr-ME">sr-ME</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sr-RS">sr-RS</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sr-SP">sr-SP</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sr-SR">sr-SR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sr-yu">sr-yu</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sv">sv</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sv_se">sv_se</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sv-SE">sv-SE</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/sw">sw</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/syste">syste</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ta">ta</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ta-TA">ta-TA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tamil">tamil</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tc">tc</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/te">te</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/th">th</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/th-th">th-th</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tk">tk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tl">tl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tl-PH">tl-PH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tr">tr</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tr_TR">tr_TR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tr-TR">tr-TR</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ts">ts</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/tw">tw</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ua">ua</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ua-UA">ua-UA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/uk">uk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/uk_UA">uk_UA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/uk-RU">uk-RU</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/uk-UA">uk-UA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/undef">undef</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ur">ur</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/ur-PK">ur-PK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/us">us</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/us-en">us-en</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/us-US">us-US</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/utf-8">utf-8</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/uz">uz</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/uz-UZ">uz-UZ</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/v-VN">v-VN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/va">va</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/va-VA">va-VA</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/val">val</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/val-V">val-V</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/vc">vc</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/vi">vi</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/vi_VN">vi_VN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/vi-VN">vi-VN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/vi|en">vi|en</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/vie">vie</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/vl">vl</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/vn">vn</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/wp-de">wp-de</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/x-def">x-def</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/yo_LO">yo_LO</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh">zh</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh_cn">zh_cn</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh_HK">zh_HK</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh_MY">zh_MY</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh_TW">zh_TW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh-CH">zh-CH</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh-cm">zh-cm</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh-CN">zh-CN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh-EN">zh-EN</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh-Ha">zh-Ha</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh-hk">zh-hk</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh-SG">zh-SG</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zh-TW">zh-TW</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zu">zu</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zxx">zxx</a></li>
        <li class="text-sm text-gray-300 "><a class="hover:text-gray-600" href="domain-list/lang/zza">zza</a></li>
        </ul>
</section>